// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class Device
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string RandomNum { get; set; }
        public double? Temp { get; set; }
        public double? Humidity { get; set; }
        public double? WindSpeed { get; set; }
        public DateTime? DateTime { get; set; }
    }
}