// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1
{
    public partial class Device
    {
        public int Id { get; set; }
        public float? Temp { get; set; }
        public float? WindSpd { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public int? RandomNum { get; set; }
        public float? Humidity { get; set; }
        public byte[] DateTime { get; set; }
    }
}