// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class OldData
    {
        public int Id { get; set; }
        public int? DeviceId { get; set; }
        public double? Temp { get; set; }
        public double? Humidity { get; set; }
        public double? SoilMoisture { get; set; }
        public double? WindSpeed { get; set; }
        public double? Gdelta { get; set; }
        public DateTime? DateTime { get; set; }
        public int? Count { get; set; }
    }
}