// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class PictureDb
    {
        public int Id { get; set; }
        public int? DeviceId { get; set; }
        public string UserName { get; set; }
        public string PictureData { get; set; }
    }
}